name: CONTENT-SFTP
 
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ main ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "SFTP"
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          host: Ranesh
          username: br789
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          
          # will put all file under this pathh 
          local_path: ./test-git-repo/.github/workflows/env.yml # default is ./*
          # files will copy to under remote_path
          remote_path: /home/br789
          

          # sftp args
          args: '-o ConnectTimeout=5'

          # Checkout the repo - uses: actions/checkout@v3 with: # Repository name with owner. For example, actions/checkout Default: ${{ github.repository }}
