name: Shell Command # this is workflow name kuch bhi dye du

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ] #this is the event, kuch bhi dye du e.g. push code, pull code, etc

jobs:
  run-shell-command:
    runs-on: ubuntu-latest # ubuntu sye linux ki commands accept krye gaa 
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script 
        run: |
           node -v 
           npm -v
      - name: python Command # will accpet python  
        run: | # kya krna chatye ho logic likho 
          import platform 
          print(platform.processor())
        shell: python # using python shell 
  
  run-windwos-commands:
    runs-on: windows-latest # now windows ki commands accept krye gaa 
    needs: ["run-shell-command"] #mene bola phelye upar wali job chalye phir yhe wali job chalye 
    steps:
      - name: Directory PowerShell # will accept Powershell 
        run: Get-Location # getting location using powershell 
      - name: Directory Bash # hum n kha bash use kra on windows 
        run: pwd #will return current path 
        shell: bash # shell specify krna lazmi hai so bash hum ko pwd return krye gaa